#!/usr/bin/env python3
import urllib.request, json, sys, re, os

def fetch_pr_diff(pr_url):
    m = re.match(r'https://github\.com/([^/]+)/([^/]+)/pull/(\d+)', pr_url)
    if not m:
        return None, "Invalid PR URL"
    owner, repo, pr_num = m.group(1), m.group(2), m.group(3)
    url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_num}"
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github.v3.diff", "User-Agent": "claude-review/1.0"})
    resp = urllib.request.urlopen(req)
    return resp.read().decode(), None

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--pr", required=True)
    args = parser.parse_args()
    diff, error = fetch_pr_diff(args.pr)
    if error:
        print(f"Error: {error}")
        sys.exit(1)
    files = [l for l in diff.split(chr(10)) if l.startswith('+++ b/')]
    print("## Review Summary")
    print(f"**Files changed:** {len(files)}")
    for f in files:
        print(f"- `{f[6:]}`")
    print()
    print("> Review generated by Claude Code PR Reviewer")

if __name__ == "__main__":
    main()
